[video_client_api]
port = 6000

[shop_event]
emit = true
url = "http://localhost:5000"
namespace = "cart"

[analyzers]
[analyzers.action]
model_path = "jwo_cv/models/action_recognition_movinet_a1_stream.pth"
min_confidence = 0.7
min_action_frame_span = 20

[analyzers.item]
model_path = "jwo_cv/models/item_detection_yolov8n.pt"
min_confidence = 0.7
max_hand_distance = 170

[analyzers.hand]
model_path = "jwo_cv/models/hand_detection_yolov8n.pt"
min_confidence = 0.6
