[general]
debug_log = false

[shop_event]
emit = true
url = "http://localhost:5000"
namespace = "cart"

[video_client_api]
port = 6000

[analyzers]
[analyzers.action]
model_path = "jwo_cv/model/action_recognition_movinet_a2_stream.pth"
min_confidence = 0.9
min_action_frame_span = 20

[analyzers.item]
model_path = "jwo_cv/config/item_detection_yolov8s.pt"
min_confidence = 0.9
max_hand_distance = 150

[analyzers.hand]
model_path = "jwo_cv/config/hand_detection_yolov8s.pt"
min_confidence = 0.6
