[video_client_api]
port = 6000

[shop_event]
emit = false
url = "http://localhost:5000"
namespace = "cart"

[analyzers]
enable = true

[analyzers.action]
model_path = "models/action_recognition_movinet_a1_stream.pth"
min_confidence = 0.5
min_action_frame_span = 20

[analyzers.item]
model_path = "models/item_detection_yolov8n.pt"
min_confidence = 0.5
max_hand_distance = 150

[analyzers.hand]
model_path = "models/hand_detection_yolov8n.pt"
min_confidence = 0.5
