[video_client_api]
port = 6000

[shop_event]
emit = false
server = "localhost:9092"

[analyzers]
enable = true

[analyzers.action]
enable = true
model_path = "models/action_recognition_movinet_a1_stream.pth"
min_confidence = 0.5
min_action_frame_span = 20

[analyzers.item]
enable = true
model_path = "models/item_detection_yolov8n.pt"
min_confidence = 0.5
min_hand_iou = 0.05

[analyzers.hand]
model_path = "models/hand_detection_yolov8n.pt"
min_confidence = 0.5
