[general]
debug_log = false
debug_video = true

[emit_events]
emit = true
server_url = "http://localhost:5000/cart"

[video_source]
source_idx = 0
size = [640, 640]

[detectors]
[detectors.action]
min_confidence = 0.4
stream_buffer_duration = 8

[detectors.item]
min_confidence = 0.5
max_hand_distance = 150

[detectors.hand]
min_confidence = 0.7
