[general]
debug_log = false
debug_video = true

[video_source]
source_idx = 0
size = [640, 640]

[detectors]
[detectors.action]
min_confidence = 0.7
stream_buffer_duration = 5

[detectors.item]
min_confidence = 0.3
max_hand_distance = 150

[detectors.hand]
min_confidence = 0.1
