[general]
debug_log = false
debug_video = true

[shopping_events]
emit = true
url = "http://localhost:5000"
namespace = "cart"

[video_client_api]
port = 5001

[detectors]
[detectors.action]
model_path = "jwo_cv/config/action_movineta2.pth"
min_confidence = 0.0005
max_buffer_frame_count = 100
min_detection_frame_span = 20

[detectors.item]
model_path = "jwo_cv/config/item_yolov8n.pt"
min_confidence = 0.5
max_hand_distance = 150

[detectors.hand]
model_path = "jwo_cv/config/hand_yolov8n.pt"
min_confidence = 0.5
