[general]
debug_video = true

[video_sources]
source_idx = 0
size = [640, 640]

[detectors]
[detectors.item_detector]
model_path = "jwo_cv/config/item_yolov8n.pt"
exclude_class_names = ["person"]
min_confidence = 0.5
max_hand_distance = 80

[logging]
version = 1

[logging.root]
level = "DEBUG"
handlers = ["console"]

[logging.formatters]
[logging.formatters.DefaultFormat]
format = "[%(asctime)s %(name)s %(levelname)s] %(message)s"

[logging.handlers]
[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "DefaultFormat"
level = "DEBUG"
stream = "ext://sys.stdout"
