[general]
debug_video = true

[video_sources]
source_idx = 0

[models]
item_classifier_model_path = "jwo_cv/config/item_yolov8n.pt"

[logging]
version = 1

[logging.root]
level = "DEBUG"
handlers = ["console"]

[logging.formatters]
[logging.formatters.DefaultFormat]
format = "[%(asctime)s %(name)s %(levelname)s] %(message)s"

[logging.handlers]
[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "DefaultFormat"
level = "DEBUG"
stream = "ext://sys.stdout"